server:
  port: 8081
  servlet:
    context-path: /identify
spring:
  application:
  name: identify-servicse
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "vqK0Iyn3p7hlP5Cw7Mgd9slRdcJbznOjKO1m4s1M6o/hwvtPDS9toxMMvGS3YTZA"
